### PR TITLE
Adding registration notification option

### PR DESCRIPTION
**Pull request by cscook**
-Corrected an oversight where not all the data from config.json was being updated with the current information after --reregister was run.
-When --reregister is run it will now print out the date/time that the number registration is valid until.
-Added an argument, --reg-notify, so you can receive an iMessage after each reregistration telling you when the number registration is valid until. You would run "demo.py --reregister --reg-notify", if you don't want to be notified you can simply keep running "demo.py --reregister".

### CODE REVIEW

**Comment by SpaceSaver** [comment]
It would be awesome if it could just take that info and reregister one minute before the registration expires.

**Comment by Kasherpete** [comment]
I don't think we found out when Apple devices know when to reregister, but I agree this is a really cool idea. I hope this gets merged.

**Comment by JJTech0130** [comment]
> I don't think we found out when Apple devices know when to reregister, but I agree this is a really cool idea. I hope this gets merged.

We did, it’s based on the expiration date on the cert

**Comment by cscook** [comment]
> It would be awesome if it could just take that info and reregister one minute before the registration expires.

On my local deployment I also added some crontab automation based on the registration expiration so this should certainly be possible, but I'm not sure it makes sense to implement that in the official pypush repository since people have many different methods of running --reregister currently. I'd be happy to share my files with the cron automation setup though.

**Comment by Kasherpete** [comment]
> > I don't think we found out when Apple devices know when to reregister, but I agree this is a really cool idea. I hope this gets merged.
> 
> We did, it’s based on the expiration date on the cert

Oh cool, we should probably implement that into the `--alive` flag. `cron` probably won't be the best option for dynamic intervals, so `cron` automation probably isn't the best idea.

**Comment by JJTech0130** [comment]
Yeah, maybe call it `--daemon` or something?

**Comment by Kasherpete** [comment]
Probably best to reuse `--alive`. Your call.

**Comment by JJTech0130** [comment]
Well, --alive should probably be removed, it was about specifically the keep alive thing. Anyway, this can be merged, the other thing can be a separate PR.

**Comment by Kasherpete** [comment]
> Well, --alive should probably be removed, it was about specifically the keep alive thing. Anyway, this can be merged, the other thing can be a separate PR.

Sounds good

**Pull request merged**
