### PR TITLE
removed daemon execution, added new script to execute daemon

### PR DESCRIPTION
**Pull request by danipoak**
The windows installer was executing the daemon at the end which wasn't working as intended. I removed that call and instead creating a new script called windows_reregister.ps1 that can be executed after initial registration to run the daemon. It includes a while loop to handle network blips.

### CODE REVIEW

**Comment by danipoak** [comment]
Readme is significantly updated to use the automated installers.

**Comment by danipoak** [comment]
Added back the manual instructions but with some errors fixed.

**Comment by danipoak** [comment]
Script links are updated to the new repo location.

**Comment by danipoak** [comment]
Last couple link fixes.

**Comment by JJTech0130** [comment]
Sorry it took so long to merge, forgot lol

**Pull request merged**
