### PR TITLE
Readme tweak for windows

### PR DESCRIPTION
**Pull request by Derakoptes**
Readme change windows

### CODE REVIEW

**Comment by Cypheriel** [comment]
Why is this necessary? Nothing about pypush requires elevated permissions.

**Comment by Derakoptes** [comment]
> Why is this necessary? Nothing about pypush requires elevated permissions.

for some reason when I was installing it kept failing without.

**Comment by SpaceSaver** [comment]
> > Why is this necessary? Nothing about pypush requires elevated permissions.
> 
> for some reason when I was installing it kept failing without.

You might've installed some dependencies where standard users don't have perms.

**Comment by Cypheriel** [comment]
> for some reason when I was installing it kept failing without.

That is certainly not a regular occurrence. I've installed on Windows multiple times just fine. If you can provide us with more details regarding your issues, perhaps we can look into it. However, with Python it's standard practice to practically NEVER do any sort of installation with elevated permissions.

**Comment by Derakoptes** [comment]
> > for some reason when I was installing it kept failing without.
> 
> That is certainly not a regular occurrence. I've installed on Windows multiple times just fine. If you can provide us with more details regarding your issues, perhaps we can look into it. However, with Python it's standard practice to practically NEVER do any sort of installation with elevated permissions.

Tried reinstalling. But couldn't recreate it for some reason. I already have everything installed though. It failed during the requirements install and I can't remember on where it froze. Maybe it was a one-time thing or the dependencies.

**Pull request closed without merging**
