### PR TITLE
Refactor for older python and add nac generator

### PR DESCRIPTION
**Pull request by SpaceSaver**
Make work on Python 3.9.2

### CODE REVIEW

**Comment by Kasherpete** [comment]
No work Python 3.9.0 or 3.8?

**Comment by SpaceSaver** [comment]
> No work Python 3.9.0 or 3.8?

Idk, my Chromebook has 3.9.2

**Comment by Kasherpete** [comment]
Should probably make work on sms-registration too

**Comment by JJTech0130** [comment]
That can be done after all the branches are cleaned up and the async stuff lands in main.

**Pull request merged**
