### PR TITLE
Create reregistration.py and update README.md

### PR DESCRIPTION
**Pull request by kymerea**
This is a short script that reregisters the phone number every 30 minutes.

Credit to @Kasherpete for creating this. I felt it should be included in the actual pypush.

Also an edit for the SMS-registration readme. Stated the basic operation of sms-registration branch. I left some blanks for some stuff I don't know and removed the 'Special Notes' section, feel free to readd it with technical information about the sms-registraion

### CODE REVIEW

**Comment by TaeHagen** [comment]
Great idea! IMO this functionality should totally be part of pypush.

I think it would be better if it could re-register in place, preferably with deregistration detection through IDS (so we don't have to invoke python every 30 minutes which is kind of a hack IMO). Then pypush would be a daemon, and take care of everything itself

FYI reregistration.py is an empty file? Think you might have forgotten to add it.

**Comment by kymerea** [comment]
> FYI reregistration.py is an empty file? Think you might have forgotten to add it.

My mistake, and yeah, I completely agree with what you say, it would be better if it was 'in-built' and not just some separate script.

**Comment by JJTech0130** [comment]
Well, I'm a little bit concerned with how it's implemented: it seems a little silly to have a python file that starts a new python interpreter, just to run another script. Wouldn't it be better to just call the main function in demo.py?

**Comment by Kasherpete** [comment]
True. I could maybe add this functionality via a flag? Like `--interval 30`?

EDIT: nevermind, read #37

**Comment by JJTech0130** [comment]
Honestly, I think that now we know how to determine exactly when a reregistration is necessary (based on cert registration), this PR is definitely not the best way to go about this.

**Pull request closed without merging**
