### PR TITLE
Add poetry support and pipx instructions

### PR DESCRIPTION
**Pull request by Cypheriel**
## Summary
The changes in this pull request aim to improve the distribution of pypush and make it easier to release a public API in the future.
Functionally, these changes should not impact pypush. The main difference is the change to the installation procedure and the newfound ability to execute pypush either via `pypush` (within `PATH`) or `python3 -m pypush` as opposed to `python3 ./demo.py`. The hope is that these changes will allow for further streamlining of the distribution process and help improve organization of the project in general.

### Notes
Changes necessary to `pyproject.toml` before merge:
- [x] Set description
- [x] Set authors

### CODE REVIEW

**Comment by Cypheriel** [comment]
If you would like to test the pipx installation process prior to merge, simply replace the GitHub URL in the installation section of the updated [README](https://github.com/Cypheriel/pypush/blob/async/README.md) with `git+https://github.com/Cypheriel/pypush@async`. I have tested on my own in WSL (openSUSE Tumbleweed) to verify that it works as intended.

**Comment by JJTech0130** [comment]
Sorry, I completely forgot about this PR since it's marked as a draft. I'll look at it later today

**Comment by JJTech0130** [comment]
So, the only thing is I've not used poetry a whole lot. How does it affect usage with normal pip? Can you still pip install pypush?

**Comment by Cypheriel** [comment]
> So, the only thing is I've not used poetry a whole lot. How does it affect usage with normal pip? Can you still pip install pypush?

~~You can see installation with pip instructions in the updated README.~~ I lied, I guess I forgot to do that. requirements.txt was moved into a new directory called requirements. Other than that, the process is the same.

**Comment by Cypheriel** [comment]
> > So, the only thing is I've not used poetry a whole lot. How does it affect usage with normal pip? Can you still pip install pypush?
> 
> ~You can see installation with pip instructions in the updated README.~ I lied, I guess I forgot to do that. requirements.txt was moved into a new directory called requirements. Other than that, the process is the same.

It would seem that I *did* actually provide the alternate instructions under the "For Developers" section of the installation instructions. `pipx` installation should be preferred. In the event `pipx` installation does not work (which ... don't exactly know what would cause such a thing), that set of installation instructions can be followed. I have tested the installation via `pipx` myself in a fresh installation of openSUSE Tumbleweed for WSL. 

Additional testers following instructions laid out in [this comment](https://github.com/JJTech0130/pypush/pull/52#issuecomment-1835432389) are welcomed!

**Note**: I grabbed authors from the "contributors" section on GitHub. If this list is inadequate, please adjust accordingly.

**Comment by Cypheriel** [comment]
Additionally worth mentioning that this pull request, if merged, will obsolete #59. This is due to the fact that `pipx` installs packages into isolated environments already. Thus, theoretically eliminating the need for manual venv creation by end-users.

**Pull request merged**
